[package]
name = "fulgor"
version = "0.1.0"
edition = "2021"
description = "A modular 3D rendering engine centered around Gaussian splatting primitives."
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/fulgor"

[lib]
name = "fulgor"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"